### ISSUE TITLE
Regarding the bug with the  prop

### ISSUE THREAD

**Issue by 59160153** [Some-Bunny/Planetside#15] opened 2024-11-11 13:49 UTC
When you have a pit lords pact, throw the self replicating blank into the pit, and the prop itself will be returned. You can use it to swipe A-level props and unlimited money out of thin air
![30a90e61a733cccc3135356d833d2945](https://github.com/user-attachments/assets/b86290b9-a611-4a4c-8f89-f0f9232dc045)
![1a72a6541f82d1d9655510de635bb5c6](https://github.com/user-attachments/assets/fa08026f-9e2a-4566-bcd6-03ed2ac91f13)
By the way, may I ask what is the mechanism for the maximum number of item exchanges per level in the pit lords pact? Why is it that sometimes I can exchange firearms and items once each, sometimes I can exchange items twice, and sometimes I can't exchange items at all and can only exchange money

**Comment by Some-Bunny** [comment] 2024-11-11 17:11
the amount of exchanges scales with the amount of pit lords pacts you have taken. every floor you recieve as many exchanges equal to the amount of pit lords pacts you have, and once you run out of exchanges on a floor it starts to just sell the item. the bug seems to be caused by certain items that are tagged to respawn if thrown into a pit, and self-replicating blank is improperly tagged to be respawned if thrown into a pit. Will be fixed

**Closed** 2024-11-12 15:26 UTC
Labels: bug
